### PR TITLE
use correct SVG attribute namespaces

### PR DESCRIPTION
**Pull request by ahdinosaur**
fixes SVG attributes such as `xlink:href`.

based on https://github.com/Matt-Esch/virtual-dom/pull/172.

### CODE REVIEW

**Comment by ashaffer** [comment]
Thx for the fix! I'm gonna merge, but would you mind updating your package to be a bit smaller? I think you can avoid creating a map of all the attributes by just checking for the the prefix. I'd just like to keep everything tiny if possible.

**Comment by ahdinosaur** [comment]
@ashaffer yep keen to minimize any modules. although as far as i understand (but maybe i don't), it seems we still want a list of all SVG attributes as before so we can distinguish between doing `setAttribute(name, value)` (for DOM elements) versus `setAttributeNS(null, name, value)` (for XML elements, such as SVG), when i get time i'm happy to split the current module into two, one as an array of all svg attributes and one as a map for the prefixes.

**Comment by ahdinosaur** [comment]
ah nevermind, [seems we're fine using `setAttribute` unless there is a namespace](http://stackoverflow.com/questions/4882890/svg-in-xhtml5-setting-attributes-with-proper-namespace), which means we don't need [an array of svg attributes](https://github.com/ahdinosaur/is-svg-attribute).

**Comment by ahdinosaur** [comment]
[updated](https://github.com/ahdinosaur/svg-attribute-namespace/blob/1.1.0/index.js), thoughts? also wonder about the expected behavior of [this](https://github.com/ahdinosaur/svg-attribute-namespace/blob/1.1.0/test.js#L12-L14).

**Comment by ashaffer** [comment]
Looks good! Thx. I'm not sure what should happen in that undefined case. Throwing an error might make sense there.

**Comment by ahdinosaur** [comment]
sweet as, https://github.com/ahdinosaur/svg-attribute-namespace/commit/9210f429661edbfad5ac147ebca759ace88ba381 and https://github.com/ashaffer/virtex-dom/issues/4. :smile_cat:

**Pull request merged**
